name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Render
        run: echo "Backend auto-deploys via Render webhook"

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: echo "Frontend auto-deploys via Vercel GitHub integration"